[workspace]
members = ["monoio-rustls", "monoio-native-tls", "monoio-io-wrapper", "example"]
resolver = "2"

[workspace.dependencies]
monoio = { version = "0.2.0" }
bytes = { version = "1" }
thiserror = { version = "1" }
